package com.example.mindrelax.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF2E7D32)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC8E6C9)
val md_theme_light_onPrimaryContainer = Color(0xFF003300)
val md_theme_light_secondary = Color(0xFF4CAF50)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8F5E9)
val md_theme_light_onSecondaryContainer = Color(0xFF002200)
val md_theme_light_tertiary = Color(0xFF006D3B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF91FBBC)
val md_theme_light_onTertiaryContainer = Color(0xFF00210E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDFA)
val md_theme_light_onBackground = Color(0xFF191C19)
val md_theme_light_surface = Color(0xFFFBFDFA)
val md_theme_light_onSurface = Color(0xFF191C19)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF717970)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF81C784)
val md_theme_dark_onPrimary = Color(0xFF00390A)
val md_theme_dark_primaryContainer = Color(0xFF005315)
val md_theme_dark_onPrimaryContainer = Color(0xFFA5F0AF)
val md_theme_dark_secondary = Color(0xFFA5D6A7)
val md_theme_dark_onSecondary = Color(0xFF00390E)
val md_theme_dark_secondaryContainer = Color(0xFF00531A)
val md_theme_dark_onSecondaryContainer = Color(0xFFC1EFB2)
val md_theme_dark_tertiary = Color(0xFF74DEA2)
val md_theme_dark_onTertiary = Color(0xFF00391B)
val md_theme_dark_tertiaryContainer = Color(0xFF00522B)
val md_theme_dark_onTertiaryContainer = Color(0xFF91FBBC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C19)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C19)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)
